[package]
name = "snowball-compiler"
version = "0.1.0"
authors = ["merl <merl.001.mia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"

[dependencies]
